/*
 * Wortlaut des Blocks `oberflaeche` in rahmen.yaml (Drehbuch docs/drehbuch-v2/04-rahmen.md Abschnitt 7; Entwurf des Rahmen-Schreibers P19.6). Die Wörter selbst stehen in
 * src/ui/woerter.ts; `tests/geschichte-oberflaeche.test.ts` hält fest, dass beide dasselbe sagen. Nur Tests, keine Auslieferung.
 */
export const OBERFLAECHE_ENTWURF: Record<string, unknown> = {
  station: "Station",
  'akt-leiste': "Die drei Akte der Geschichte",
  'rest-gleich': "gleich geschafft",
  'rest-minuten': "noch etwa {min} Minuten",
  'ort-pause': "Pause nach {akt}",
  'pause-kicker': "Kurze Pause",
  'kann-jetzt': "Das können Sie jetzt",
  'pause-weiter': "Weiter mit {akt}",
  'pause-offen': "Einige Stationen dieses Akts haben Sie noch nicht gespielt.",
  'zur-offenen': "Zur ersten offenen Entscheidung: {stelle} · {titel}",
  gespeichert: "Ihr Weg bis hier ist auf diesem Gerät gespeichert.",
  'weiter-kicker': "Was dazwischen geschah",
  'weiter-ganz': "Weiter mit der ganzen Geschichte",
  'bruecken-kicker': "Inzwischen",
  buch: "Entscheidungsbuch",
  'buch-titel': "Das Entscheidungsbuch",
  'buch-intro': "Hier hält die Projektsteuerin fest, was beschlossen wurde und was nicht, auf welcher Grundlage und wer entschieden hat. Sie lesen mit.",
  'buch-leer': "Noch steht nichts im Buch. Mit der ersten Station beginnt es sich zu füllen.",
  'buch-legende': "Beschluss: Die zuständige Stelle hat entschieden. Vermerk: Es wurde etwas festgehalten, aber nichts beschlossen. Übergabe: Offenes geht mit Termin und Namen an einen Nachfolger.",
  'buch-spalten': ["Anlass", "Entschieden von", "Grundlage", "Ergebnis"],
  'buch-art': {"beschluss": "Beschluss", "vermerk": "Vermerk", "uebergabe": "Übergabe", "beschluss-uebergabe": "Beschluss und Übergabe"},
  'buch-neu': "neu",
  'buch-zeigen': "Entscheidungsbuch zeigen",
  'buch-druck-titel': "Entscheidungsbuch · Schulcampus Lindenhall-Süd (fiktiver Fall)",
  'verlauf-pause': "Ihr Weg bis hier",
  'verlauf-bilanz': "Ihr Weg im Überblick",
  'verlauf-text': "Verlauf als Text",
  'verlauf-legende': "Die Linien zeigen, wie sich Geld, Zeit und Vertrauen von Station zu Station verändert haben. Die Streifen dahinter heißen „gut gefüllt“, „etwa halb voll“ und „knapp“.",
  'verlauf-hohl': "Hohle Punkte: Diese Stationen wurden nur erzählt.",
  'verlauf-offen': "noch offen",
  vertiefung: "Vertiefung",
  'vertiefung-formen': {"nachdenken": "Zum Nachdenken", "zweiter-fall": "Ein zweiter Fall", "warum-so": "Warum so?"},
  'vertiefung-antwort': "Antwort",
  'mini-kicker': "Mini-Aufgabe",
};
