/*
 * Bedienbeschriftungen (Knöpfe, Labels, Hinweise zur Bedienung) an einer Stelle.
 *
 * Alles, was erzählt oder fachlich etwas aussagt, steht in inhalte/ (O-18) und kommt über
 * src/generiert/inhalte.json. Hier stehen nur Wörter der Bedienung – so bleibt prüfbar, dass kein
 * Story- oder Fachtext im Code steckt. Mehrsprachig später: diese Datei je Sprache.
 */

/** Kleine Anzahlen als Wort am Satzanfang (Startseite). */
const ZAHLWORT: Record<number, string> = { 2: 'Zwei', 3: 'Drei', 4: 'Vier', 5: 'Fünf', 6: 'Sechs', 7: 'Sieben', 8: 'Acht', 9: 'Neun', 10: 'Zehn', 11: 'Elf', 12: 'Zwölf' };

export const W = {
  // O-33: Der Name des Programms; Bauherr Mentoren bleibt mit Bildmarke und als Herausgeber genannt –
  // O-34: zurückhaltend, an der Sache orientiert (im Rahmen nur als Herausgeber, nicht im Produktnamen)
  name: 'Governance Kompass',
  adresse: 'www.GovernanceKompass.de',
  langname: 'Minimum Viable Governance',
  produkt: 'Governance Kompass – Minimum Viable Governance',
  absender: 'Bauherr Mentoren',
  herausgeber: 'Herausgeber: Bauherr Mentoren',
  fiktiv: 'Fiktiver Fall',
  story: 'Story',
  version: (fassung: string) => `Fassung ${fassung}`,
  // Start
  start: {
    // Kicker, Leitsatz und These stehen in inhalte/start.md.
    wege: 'Drei Wege',
    internetseite: 'Der Governance Kompass ist eine Internetseite – zum Lesen und Ausprobieren, ohne Anmeldung, ohne Konto.',
    storyKicker: 'Erlebt',
    storyTitel: 'Als Geschichte',
    storyText: 'Sie leiten für die Stadt Lindenhall den Bau eines Schulcampus. Unterwegs entscheiden Sie achtmal – und sehen gleich, was jede Wahl für Geld, Zeit und Vertrauen bedeutet.',
    // Anzahl als Wort; sichtbar nie „Kapitel“ (O-38, L-225)
    storyMeta: (n: number) => `${ZAHLWORT[n] ?? String(n)} Entscheidungen · etwa 25 Minuten, kurz etwa 10`,
    storyLos: 'Beginnen',
    storyWeiter: 'Weiterlesen',
    figuren: 'Mit dabei',
    theorieKicker: 'Erklärt',
    theorieTitel: 'In Themen',
    theorieText: 'Was Minimum Viable Governance ausmacht – wie ein Buch in vier Teilen, mit Grafiken zum Anklicken.',
    theorieMeta: (n: number) => `${n} Themen · einzeln lesbar`,
    theorieLos: 'Öffnen',
    exploreKicker: 'Ausprobiert',
    exploreTitel: 'Werkzeuge',
    exploreText: 'Gewichte verschieben, Risiken einordnen, Vorgänge verfolgen – am selben Schulcampus.',
    exploreMeta: (n: number) => `${n} Werkzeuge`,
    exploreLos: 'Ausprobieren',
    dahinter: 'Wer steht dahinter',
    dahinterText: 'Der Governance Kompass ist ein Angebot der Bauherr Mentoren GmbH i. G. Fragen, Kontakt und alles Weitere:',
    fiktiv: 'Der Schulcampus Lindenhall-Süd ist ein fiktiver Fall; Stadt, Projekt und Personen sind erfunden.',
  },
  // Druck (P10.2, E11)
  druck: {
    stand: (datum: string) => `Druck vom ${datum}`,
    // R47: Strg+P auf Flächen ohne eigenen Druckbogen
    ersatzTitel: 'Governance Kompass · Druckfassungen',
    ersatzText: 'Diese Ansicht ist für den Bildschirm gedacht. Gedruckt wird über diese Wege:',
    ersatzWege: [
      'Theorie: „Thema drucken“ auf jeder Seite eines Themas.',
      'Präsentieren: „Protokoll drucken“ – Notizen und Entscheidungen des Gesprächs.',
    ],
  },
  ebene: 'Ebene',
  // Theorie
  // Kleine interaktive Grafiken der Lernseiten (P12.3, O-30)
  lernwerkzeug: {
    etappen: 'Etappen',
    etappeVon: (i: number, n: number) => `Etappe ${i} von ${n}`,
    etappeAnsage: (i: number, n: number, titel: string) => `Etappe ${i} von ${n}: ${titel}`,
    zurueck: 'Zurück',
    weiter: 'Weiter',
    umschalter: 'Ansicht wählen',
    zuordnen: 'Zuordnen',
    passt: 'Passt.',
    gehoertZu: (korb: string) => `Gehört zu: ${korb}.`,
    sortierStand: (i: number, n: number) => `${i} von ${n} zugeordnet`,
    aufloesen: 'Alle auflösen',
    regler: 'Stufe wählen',
  },
  theorie: {
    wissenscheck: 'Kurz geprüft',
    wissenscheckAntworten: 'Ihre Einschätzung',
  },
  // Abbildungen im Fachtext (P14, O-32, L-77; nur Marke und Titel, O-56)
  abbildung: {
    marke: (nr: number) => `Abbildung ${nr}`,
    fehlt: 'Bild nicht eingebettet',
  },
  // Regie
  regie: {
    titel: 'Regie',
    zurueck: 'Zurück',
    weiter: 'Weiter',
    themenUebersicht: 'Übersicht der Themen',
    tafel: 'Leinwand rollen',
    tafelHoch: 'Tafel bzw. Lernseite auf der Leinwand hochrollen',
    tafelRunter: 'Tafel bzw. Lernseite auf der Leinwand runterrollen',
    tafelHinweis: '↑ ↓ oder Pfeiltasten: Tafel der Story bzw. Lernseite, wenn sie länger ist als die Leinwand',
    leinwandOeffnen: 'Leinwand öffnen',
    verbunden: 'Leinwand verbunden',
    nichtVerbunden: 'Leinwand nicht verbunden',
    vorschau: 'Vorschau der Leinwand',
    notiz: 'Regie-Notiz',
    leitfragen: 'Leitfragen',
    beamer: 'Beamer: groß und kontrastreich',
    sprung: 'Springen zu',
    protokollDrucken: 'Protokoll drucken',
    protokollLoeschen: 'Protokoll löschen',
    druckTitel: 'Gesprächsprotokoll',
    druckEintraege: 'Notizen aus dem Gespräch',
    druckLeer: 'Keine Einträge.',
    druckEntscheidungen: 'Entscheidungen in der Geschichte',
    sprungWaehlen: 'Schritt wählen …',
    schritteHier: 'Schritte',
    wertung: { gut: 'gut', vertretbar: 'vertretbar', falle: 'Falle' } as Record<string, string>,
    wertungTitel: 'Wertung (nur in der Regie)',
    antwortNr: (nr: number) => `Antwort ${nr}`,
    wahlZurueck: 'Wahl zurücknehmen',
    miniAufloesen: 'Auflösen',
    miniLeeren: 'Zurücksetzen',
    miniLoesung: 'richtig',
    miniReiheHinweis: 'Schritte in der Reihenfolge anklicken, die die Runde ansagt; ein zweiter Klick löst den Schritt und alle danach.',
    keineNotiz: 'Für diesen Schritt gibt es keine Notiz.',
    kundenwahl: 'Kundenwahl und Eingriffe',
    keineEingriffe: 'An diesem Schritt gibt es nichts zu wählen.',
    bereich: 'Fläche',
    start: 'Start',
    protokoll: 'Gesprächsprotokoll',
    protokollFeld: 'Notiz zum Gespräch',
    protokollSichern: 'Ins Protokoll',
    nurRegie: 'Nur in der Regie sichtbar – erreicht die Leinwand nie.',
  },
  leinwand: {
    titel: 'Leinwand',
    warten: 'Die Leinwand wartet auf die Regie.',
    wartenHinweis: 'Öffnen Sie „Präsentieren“ in einem anderen Fenster desselben Browsers.',
  },
  // Rahmen aller Bereiche (P16.11, O-42, O-44)
  rahmen: {
    theorie: 'Theorie',
    explore: 'Explore',
    bereiche: 'Bereiche',
    bmMarke: 'Bauherr Mentoren – bauherr-mentoren.com',
    angebot: 'Ein Angebot von',
    kontaktBm: 'Kontakt über bauherr-mentoren.com',
    rechtliches: 'Rechtliches und Präsentieren',
    impressum: 'Impressum',
    datenschutz: 'Datenschutz',
    praesentieren: 'Präsentieren',
    zumInhalt: 'Zum Inhalt springen',
  },
  // Story (P17.4, O-51/O-52): acht Kapitel, drei Antworten, Balken Geld · Zeit · Vertrauen
  geschichte: {
    fortschritt: 'Fortschritt der Geschichte',
    vonN: (nr: number, n: number) => `${nr} von ${n}`,
    auftakt: 'Auftakt',
    ende: 'Schulstart',
    // Teile eines Kapitels (Regie: wo die Bühne steht)
    teile: { szene: 'Szene', vergleich: 'Vergleich', frage: 'Frage', mini: 'Mini-Aufgabe' } as Record<string, string>,
    weiter: 'Weiter',
    zurueck: 'Zurück',
    vonVorn: 'Noch einmal von vorn',
    zuDenThemen: 'Zu den Themen',
    kurzfassung: 'Kurzfassung',
    fiktiv: 'Fiktiver Fall',
    sie: 'Sie',
    sieRolle: 'Projektleitung der Stadt',
    steckbrief: 'Steckbrief',
    balkenTitel: 'Drei Balken begleiten Sie',
    balkenLeiste: 'Stand von Geld, Zeit und Vertrauen',
    // Füllstand in Worten (nie nur Farbe; ohne Zahlen)
    fuellstand: { hoch: 'gut gefüllt', mittel: 'etwa halb voll', niedrig: 'knapp' } as Record<string, string>,
    etwas: 'etwas',
    deutlich: 'deutlich',
    unveraendert: 'unverändert',
    bleibtOben: 'bleibt ganz oben',
    bleibtUnten: 'bleibt ganz unten',
    szeneTitel: 'Im Gespräch',
    ihreEntscheidung: 'Ihre Entscheidung',
    antworten: 'Drei Antworten',
    gewaehlt: 'Ihre Wahl',
    nochKeineWahl: 'Bitte wählen Sie eine der drei Antworten.',
    folgeTitel: 'So geht es weiter',
    wirkungTitel: 'Was Ihre Antwort bewegt',
    gutTitel: 'So macht man es gut',
    dahinterTitel: 'Das steckt dahinter',
    zumThema: 'Zum Thema',
    mandatZeigen: 'Wer entscheidet was',
    brueckeTitel: 'Was inzwischen geschah',
    miniKicker: 'Mini-Aufgabe',
    miniRichtig: 'Richtig',
    miniFalsch: (loesung: string) => `Nicht ganz – richtig ist: ${loesung}.`,
    miniStelle: (n: number) => `an Stelle ${n}`,
    miniGehoert: (n: number) => `gehört an Stelle ${n}`,
    miniErgebnis: (richtig: number, n: number) => `${richtig} von ${n} richtig.`,
    miniNochmal: 'Noch einmal',
    miniNoch: (n: number) => `Noch ${n} offen.`,
    vergleichKicker: 'Der Vergleich',
    vergleichTitel: 'Drei Wege, vier Gesichtspunkte',
    wasWichtiger: 'Was ist wichtiger?',
    stufen: { 5: 'sehr wichtig', 3: 'wichtig', 1: 'weniger wichtig' } as Record<number, string>,
    abgestimmt: 'abgestimmt',
    abgestimmteGewichte: 'Abgestimmte Gewichte',
    platz: (n: number) => `Platz ${n}`,
    punkteVon: (n: number) => `${n} von 5 Punkten`,
    punkte: (n: number) => `${n} Punkte`,
    vorn: (titel: string, punkte: number) => `Vorn liegt „${titel}“ mit ${punkte} Punkten.`,
    gleichauf: (titel: readonly string[], punkte: number) => `Gleichauf vorn: ${titel.map((t) => `„${t}“`).join(' und ')} mit je ${punkte} Punkten.`,
    kippTitel: 'Wann kippt die Rangfolge?',
    kippKeiner: 'Keine einzelne andere Stufe ändert, wer vorn liegt.',
    kipp: (kriterium: string, stufe: string, wer: readonly string[]) => wer.length > 1
      ? `Wäre ${kriterium} ${stufe}, lägen ${wer.map((t) => `„${t}“`).join(' und ')} gleichauf.`
      : `Wäre ${kriterium} ${stufe}, läge „${wer[0] ?? ''}“ vorn.`,
    projektsteuerinSagt: 'Die Projektsteuerin',
    bilanzTitel: 'Ihre Bilanz',
    offen: (n: number) => n === 1 ? 'Eine Entscheidung haben Sie noch nicht getroffen – sie zählt hier nicht mit.' : `${n} Entscheidungen haben Sie noch nicht getroffen – sie zählen hier nicht mit.`,
    fortschrittLoeschen: 'Fortschritt löschen',
    fortschrittHinweis: 'Ihr Stand liegt nur in diesem Browser.',
    druckTitel: 'Ihre Geschichte',
    druckAntwort: 'Ihre Antwort',
    druckOffen: 'noch offen',
    druckBruecke: 'in der Kurzfassung erzählt',
    // Rechner in Explore (gewichteter Vergleich mit Gewichten 1–5)
    kriterium: 'Kriterium',
    gewicht: 'Gewicht',
    summe: 'Summe',
    rang: (r: number) => `Rang ${r}`,
    kipppunkte: 'Wann sich die Spitze dreht',
    keinKipppunkt: 'Kein einzelnes Gewicht zwischen 1 und 5 dreht die Spitze.',
    kipppunkt: (kriterium: string, gewicht: number, wer: string[]) => wer.length > 1 ? `${kriterium} auf ${gewicht}: Gleichstand – ${wer.join(' und ')}` : `${kriterium} auf ${gewicht}: vorn läge ${wer[0] ?? ''}`,
  },
  // Theorie als Themen (P16.3, O-38)
  themen: {
    bereich: 'Theorie',
    titel: 'Die Themen',
    einleitung: 'Minimum Viable Governance in vier Teilen – vom Überblick bis zu den Werkzeugen der Praxis. Jedes Thema ist für sich lesbar.',
    // Buch (P17.8, O-54): Teile I–IV und Anhang, Nummer vor dem Titel (nie „Kapitel“, O-38)
    teil: (n: 1 | 2 | 3 | 4) => `Teil ${['I', 'II', 'III', 'IV'][n - 1] ?? ''}`,
    teilName: { 1: 'Grundlagen', 2: 'Führungsmodell und Arbeitsweise', 3: 'Anwendung und Einführung', 4: 'Werkzeuge der Praxis' } as Record<1 | 2 | 3 | 4, string>,
    anhang: 'Anhang',
    nummer: (nr: number, titel: string) => `${nr} · ${titel}`,
    inhaltsverzeichnis: 'Inhaltsverzeichnis',
    fortschritt: 'Ihr Fortschritt',
    geschafftZahl: (n: number, gesamt: number) => `${n} von ${gesamt} geschafft`,
    geschafft: 'geschafft',
    zuruecksetzen: 'Fortschritt zurücksetzen',
    verzeichnis: 'Themen',
    lesen: 'Lesen',
    kernaussage: 'Kernaussage',
    // Karten mit Rückseite (P17.9, O-55): umdrehen per Knopf; die Ansage nennt die sichtbare Seite
    karteUmdrehen: 'Umdrehen',
    karteVorderseite: 'Vorderseite',
    karteRueckseite: 'Rückseite',
    karteZeigt: (seite: string, titel: string) => `${titel}: ${seite}`,
    blaettern: 'Themen blättern',
    zurueck: 'Zurück',
    weiter: 'Weiter',
    inDerStory: 'In der Story erlebt',
    drucken: 'Thema drucken',
    kontakt: 'Fragen zur Umsetzung im eigenen Projekt?',
    glossar: 'Glossar',
    glossarSuche: 'Begriff oder Wort suchen',
    glossarZahl: (n: number, gesamt: number) => n === gesamt ? `${gesamt} Begriffe` : `${n} von ${gesamt} Begriffen`,
    glossarLeer: 'Kein Begriff passt zur Suche.',
    kommtVor: 'Mehr dazu in',
    kompass: 'Begriffs-Kompass',
    kompassText: 'Andere Organisationen sagen oft anders, was hier gemeint ist. Die Tabelle ist eine Lesehilfe: links gängige Bezeichnungen, rechts der Begriff des Governance Kompass. Die Zuordnung ist keine Gleichsetzung im Detail.',
    kompassAndere: 'Andernorts oft',
    kompassBegriff: 'Hier',
    tabelle: (titel: string) => `Tabelle: ${titel}`,
    unbekannt: 'Dieses Thema gibt es nicht. Hier sind alle Themen.',
  },
  // Explore-Werkzeuge (P16.8, O-46)
  werkzeuge: {
    bereich: 'Explore',
    werkzeuge: 'Werkzeuge',
    keinBeispiel: 'Kein Beispiel vorhanden.',
    beispiel: 'Beispiel aus der Story',
    zuruecksetzen: 'Auf die Werte der Vorlage zurücksetzen',
    mcdaTabelle: 'Gewichteter Vergleich, Punkte und Gewichte einstellbar',
    punkteHinweis: (min: number, max: number) => `Gewichte und Punkte je ${min} bis ${max}. Die Begründung unter jedem Punkt ist die der Vorlage; wer Punkte ändert, muss sie neu begründen.`,
    wahrscheinlichkeit: 'Wahrscheinlichkeit',
    auswirkung: 'Auswirkung',
    immerVorrangig: 'Auswirkung 5 ist immer vorrangig',
    qualitaetStufe: (n: number) => `Zum Vergleich – Auswirkung ${n} bei Qualität oder Funktion:`,
    zelle: (w: number, a: number, wert: number, stufe: string, n: number) => `Wahrscheinlichkeit ${w}, Auswirkung ${a}: ${wert}, ${stufe}${n > 0 ? `, ${n} Beispiel${n > 1 ? 'e' : ''}` : ''}`,
    beispielVorgang: 'Im Beispiel',
    abschluss: 'Geschlossen, wenn',
    wege: 'Kann weiterführen zu',
    monatsAblauf: 'Ein Monat im Takt',
    woche: (n: number) => `Woche ${n}`,
    wochenPruefung: 'Alle offenen Vorgänge prüfen',
    dringlich: 'Dringliches sofort',
    monatsTermin: 'Monatstermin und Bericht',
    imBeispiel: 'Im Beispiel',
  },
} as const;
