/*
 * Bedienbeschriftungen (Knöpfe, Labels, Hinweise zur Bedienung) an einer Stelle.
 *
 * Alles, was erzählt oder fachlich etwas aussagt, steht in inhalte/ (O-18) und kommt über
 * src/generiert/inhalte.json. Hier stehen nur Wörter der Bedienung – so bleibt prüfbar, dass kein
 * Story- oder Fachtext im Code steckt. Mehrsprachig später: diese Datei je Sprache.
 */

export const W = {
  produkt: 'Minimum Viable Governance – ein interaktives Whitepaper von Bauherr Mentoren',
  absender: 'Bauherr Mentoren',
  fiktiv: 'Fiktiver Fall',
  ungeprueft: 'fachlich ungeprüft',
  whitepaper: 'Whitepaper',
  story: 'Story',
  version: (whitepaper: string, story: string) => `Whitepaper ${whitepaper} · Story ${story}`,
  // Start
  start: {
    // Kicker, Leitsatz und These stehen in inhalte/start.md (fachliche Aussage, O-17/O-18).
    wegWaehlen: 'Wählen Sie Ihren Weg.',
    wege: 'Zwei Wege',
    theorieKicker: 'Erklärt',
    theorieTitel: 'Kapitel für Kapitel',
    theorieText: 'Die gesamte MVG-Theorie in den 13 Kapiteln des Whitepapers, mit Grafiken zum Anklicken und dem Originaltext zum Nachlesen.',
    theorieMeta: (n: number) => `${n} Kapitel · in Etappen lesbar`,
    theorieLos: 'Öffnen',
    storyKicker: 'Erlebt',
    storyTitel: 'Als Geschichte',
    storyText: 'Zwei Welten, ein Schulcampus. Sie übernehmen eine Rolle und treffen die Entscheidungen, einmal ohne und einmal mit MVG.',
    storyMeta: (rollen: number) => `ca. 30 Minuten · ${rollen} Rollen`,
    storyLos: 'Beginnen',
    storyWeiter: 'Weiterlesen',
    weltA: 'Welt A · ohne MVG',
    weltB: 'Welt B · mit MVG',
    fuss: 'Ein interaktives Whitepaper von Bauherr Mentoren',
    praesentieren: 'Präsentieren',
    interaktiv: 'interaktiv',
  },
  // Leitstand
  kopfTitelFallback: 'Zwei Welten',
  zurStart: 'Zur Startseite',
  zurTafel: 'Zur Lagetafel springen',
  weltA: 'Welt A',
  weltB: 'Welt B',
  ohneMvg: 'ohne MVG',
  mitMvg: 'mit MVG',
  vorschau: 'Vorschau',
  weltVergleich: 'Welt A ⟷ Welt B',
  karte: 'Story-Karte',
  /** Absender = Figur der gespielten Rolle (H13) */
  sieSelbst: 'Sie',
  /** LPH-Band (O-14): Beschriftung für Screenreader */
  lphBand: 'Leistungsphasen LPH 0–9',
  lphJetzt: 'aktuell',
  lphAbgeschlossen: 'zurückliegend',
  station: 'Station',
  monat: 'Monat',
  rolle: 'Rolle',
  zurueck: 'Zurück',
  weiter: 'Weiter',
  ende: 'Ende',
  schritte: 'Schritte der Station',
  schritt: 'Schritt',
  teile: 'Teile',
  lagetafel: 'Lagetafel',
  // Szenen
  posteingang: 'Posteingang',
  neu: '1 neu',
  betreff: 'Betreff',
  anhang: 'Anhang',
  randnotizen: 'Randnotizen',
  bekannt: 'Bekannt',
  unbekannt: 'Unbekannt',
  neuBekannt: 'neu bekannt',
  lage: 'Lage',
  optionen: 'Optionen',
  optionenHinweis: ['Klick oder Taste', 'Richtig oder falsch gibt es hier nicht – nur Folgen.'] as const,
  ihreWahl: 'Ihre Wahl',
  andereWahl: 'Andere Wahl',
  keineWahl: 'Noch keine Wahl getroffen.',
  status: 'Status',
  statusUnveraendert: 'Status unverändert',
  konsequenz: 'Konsequenz',
  wasFehlt: 'Was fehlt',
  neuesRisiko: 'Neues Risiko',
  governanceFrage: 'Governance-Frage',
  reglerHinweis: 'Regler ziehen, antippen oder mit ← → umschalten',
  regler: 'Vergleich Welt A – Welt B',
  sieSindHier: 'Sie sind hier',
  weltAChaos: 'Welt A · Durcheinander',
  weltBFluss: 'Welt B · Governance-Fluss',
  zeitsprung: 'Zeitsprung',
  tage: 'Tage',
  datenstandTitel: 'Verbindlicher Datenstand',
  verbindlich: 'verbindlich',
  zumVergleich: 'Zum Vergleich: Welt A',
  stufe: 'Stufe',
  musterMandatsleiter: 'Muster-Mandatsleiter (Kap. 4.2)',
  mandatFrage: 'Welche Option liegt auf dem Tisch?',
  option: 'Option',
  zustaendig: (betrag: string) => `Zuständig bei ${betrag}`,
  rueckmeldungWarten: 'Die Rückmeldung erklärt – sie vergibt keine Punkte.',
  ihreEinschaetzung: 'Ihre Einschätzung',
  erinnert: 'Die Geschichte erinnert sich',
  ihreWahlA: 'Ihre Wahl in Welt A',
  weltBErinnert: 'Welt B erinnert sich',
  ihreFruehereWahl: 'Ihre frühere Wahl',
  weltAErinnert: 'Was davon bleibt',
  ohneWahlA: 'Ohne Wahl in Welt A',
  derselbeMoment: 'derselbe Moment',
  nachWahl: (w: string) => `nach Wahl ${w}`,
  ebene: 'Ebene',
  fuerSieVertieft: 'Für Sie vertieft',
  spuleZurueck: (m: number) => `Zeitleiste der Welt A läuft von Monat ${m} zurück auf Monat 0`,
  ebenen: 'Ebenen',
  originalWoertlich: 'Originaltext, wörtlich',
  projektUebernehmen: 'Projekt übernehmen',
  folgt: 'folgt',
  spielbar: 'spielbar',
  auswaehlen: 'Diese Rolle übernehmen',
  fallDaten: { stadt: 'Stadt', bauherr: 'Bauherr', vertretung: 'vertreten durch', projekt: 'Projekt', projektbasis: 'Projektbasis', bauweise: 'Bauweise' },
  besetzung: 'Besetzung',
  // Einheiten der Instrumente: Risiken „aktiv“, Entscheidungen „offen“ (Status nach Kap. 6.4.4)
  einheit: { vonFuenf: 'von 5', aktiv: 'aktiv', offen: 'offen' },
  // Seitenleiste
  seite: {
    kontext: 'Kontext',
    rollenLinse: 'Rollen-Linse',
    siespielen: 'Sie spielen',
    standpunkt: 'Standpunkt wechseln',
    raum: 'Im Raum',
    ebenen: 'Ebenen',
    glossar: 'Glossar',
    quellen: 'Quellen',
    quellenHinweis: 'Die Absätze des Whitepapers, auf die sich diese Station stützt – wörtlich, mit Kapitel und Absatz.',
    keineQuellen: 'Diese Station verweist auf keinen Absatz des Whitepapers.',
    quellAngabe: (fassung: string, abschnitt: string, id: string) => `Whitepaper ${fassung}, Kap. ${abschnitt} · ${id}`,
    imRaum: 'Im Raum',
    monat: 'Monat',
    fall: 'Der Fall',
    projekt: 'Projekt',
    projektbasis: 'Projektbasis',
    stand: 'Stand',
    bauherr: 'Bauherr',
    vertretung: 'vertreten durch',
    tasten: 'Tasten: ← → blättern · A–D wählen · Esc schließt',
    einklappen: 'Einklappen',
    neu: 'Neu',
    glossarHinweis: 'Unterstrichene Begriffe auf der Lagetafel zeigen ihre Definition bei Mausberührung, Antippen oder Tastaturfokus.',
    ebenenHinweis: 'Schritt für Schritt tiefer – von der Kernaussage bis zum Originaltext.',
    keineEbenen: 'An dieser Station gibt es noch keine Ebenen.',
    quelle: 'Definitionen wörtlich aus dem Glossar des Whitepapers.',
    zitatWort: 'Originaltext, wörtlich',
    ebene: 'Ebene',
  },
  linse: {
    rollenLinse: 'Rollen-Linse',
    titel: 'Standpunkt wechseln',
    schliessen: 'Schließen',
    unter: (uhr: string | null) => `${uhr ?? 'Derselbe Moment'} – andere Blickwinkel auf denselben Moment:`,
    zurueck: (rolle: string) => `Zurück zur Rolle ${rolle}`,
    folgt: 'folgt',
  },
  glossarQuelle: (fassung: string) => `Glossar · Whitepaper ${fassung}`,
  // Theorie
  theorie: {
    bereich: 'Erklärt',
    bereichZusatz: '· Kapitel für Kapitel',
    start: 'Start',
    kapitel: 'Kapitel',
    ueberblick: 'Alle Kapitel des Whitepapers',
    ueberblickText: 'Die Theorie folgt der Gliederung des Whitepapers. Kapitel mit Lernseite lassen sich öffnen; die übrigen folgen.',
    folgt: 'folgt',
    lernseite: 'Lernseite',
    kernaussage: 'Kernaussage',
    originaltext: (fassung: string) => `Originaltext ${fassung} · wörtlich`,
    kapitelVon: (nr: string) => `Kapitel ${nr}`,
    zurueckKap: (nr: string) => `Zurück · Kapitel ${nr}`,
    weiterKap: (nr: string) => `Weiter · Kapitel ${nr}`,
    folgtText: 'Die Lernseite zu diesem Kapitel folgt. Bis dahin: Kapitel 1 und die Story.',
    zurListe: 'Zur Kapitelliste',
    aufklappen: 'Aufklappen',
    inDerStory: 'In der Story erlebt',
    zumInhalt: 'Zum Inhalt springen',
  },
  // Explore (P2.4 Rahmen; die Werkzeuge baut P8)
  explore: {
    bereich: 'Explore',
    bereichZusatz: '· selbst ausprobieren',
    titel: 'Werkzeuge zum Ausprobieren',
    einstieg: 'Hier probieren Sie die Logik der Geschichte an eigenen Werten aus. Die Werkzeuge entstehen Schritt für Schritt; freigeschaltet wird Explore mit dem Ende der Geschichte.',
    freigeschaltet: 'Freigeschaltet',
    gesperrt: 'Nach dem Ende der Geschichte',
    inVorbereitung: 'in Vorbereitung',
    selbstAusprobieren: 'Selbst ausprobieren',
    besetzung: 'Die Besetzung des Falls',
    besetzungText: 'Zehn Figuren, drei Gesichter: gelassen, besorgt, erleichtert. Die Stimmen stehen in der Fall-Bibel.',
    mimik: { neutral: 'gelassen', besorgt: 'besorgt', erleichtert: 'erleichtert' },
    stimme: 'Stimme',
    werkzeuge: [
      { id: 'simulator', titel: 'Szenario-Simulator', text: 'Kostenabweichung, Terminabweichung, Risiken und Entscheidungsstatus eingeben – Eskalationsstufe, Informationsbedarf und Freigabeweg ablesen.' },
      { id: 'welten', titel: 'Vorher/Nachher-Welten', text: 'Informationswege, Rollen, Entscheidungen, Eskalationen, Register, Reporting und Gremien in Welt A und Welt B nebeneinander.' },
      { id: 'sandbox', titel: 'Governance-Fluss-Sandbox', text: 'Ereignisse einwerfen – Frühwarnung, Problem, Änderung – und durch Register, Status und Rollen laufen sehen.' },
      { id: 'zeitmaschine', titel: 'Zeitmaschine', text: 'Die Zeitachse schieben und sehen, wie sich Kostenunsicherheit und Entscheidungsstau in beiden Welten entwickeln.' },
      { id: 'galerie', titel: 'Grafik-Galerie', text: 'Alle Diagramme des Whitepapers, interaktiv, mit Abbildungsverzeichnis.' },
      { id: 'figuren', titel: 'Figuren und Story-Karte', text: 'Die Besetzung des Falls und jede Station der Geschichte zum direkten Sprung.' },
    ],
  },
  // Regie
  regie: {
    titel: 'Regie',
    leinwandOeffnen: 'Leinwand öffnen',
    verbunden: 'Leinwand verbunden',
    nichtVerbunden: 'Leinwand nicht verbunden',
    vorschau: 'Vorschau der Leinwand',
    notiz: 'Regie-Notiz',
    leitfragen: 'Leitfragen',
    keineNotiz: 'Für diesen Schritt gibt es keine Notiz.',
    kundenwahl: 'Kundenwahl und Eingriffe',
    keineEingriffe: 'An diesem Schritt gibt es nichts zu wählen.',
    bereich: 'Fläche',
    story: 'Story',
    theorie: 'Theorie',
    start: 'Start',
    protokoll: 'Gesprächsprotokoll',
    protokollFeld: 'Notiz zum Gespräch',
    protokollSichern: 'Ins Protokoll',
    einwaende: 'Einwand-Karten',
    einwand: 'Einwand',
    antwort: 'Antwort',
    ort: 'Ort',
    nurRegie: 'Nur in der Regie sichtbar – erreicht die Leinwand nie.',
  },
  leinwand: {
    titel: 'Leinwand',
    warten: 'Die Leinwand wartet auf die Regie.',
    wartenHinweis: 'Öffnen Sie die Regie (#regie) in einem anderen Fenster desselben Browsers.',
  },
} as const;
